### ISSUE TITLE
Animation works incorrectly in landscape device orientation

### ISSUE THREAD

**Issue by vmeretin** [marianocordoba/fab-circular-menu#9]

**Comment by marianocordoba** [comment]
Fixed in version 1.0.0

**Comment by likhithdevadiga** [comment]
Can we open this issue?
I m still facing that issue. End buttons cant be tapped in landscape mode.
